"""init

Revision ID: 43c9855ab40e
Revises: 
Create Date: 2026-07-28 16:06:10.420806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c9855ab40e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_log_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chinese_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('default_amount', sa.Float(), nullable=True),
    sa.Column('common_amounts', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_log_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('spa_platform_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('spa_platform_id')
    )
    op.create_table('work_log_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['work_log_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_log_worksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['work_log_employees.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['work_log_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_log_worksheets_date'), 'work_log_worksheets', ['date'], unique=False)
    op.create_index('ix_worksheets_date', 'work_log_worksheets', ['date'], unique=False)
    op.create_index('ix_worksheets_employee', 'work_log_worksheets', ['employee_id'], unique=False)
    op.create_table('work_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('raw_handwriting_image', sa.Text(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('confirmed_notation', sa.Text(), nullable=True),
    sa.Column('massage_base', sa.Float(), nullable=True),
    sa.Column('massage_cash', sa.Float(), nullable=True),
    sa.Column('massage_card', sa.Float(), nullable=True),
    sa.Column('facial_cash', sa.Float(), nullable=True),
    sa.Column('facial_card', sa.Float(), nullable=True),
    sa.Column('card_tip', sa.Float(), nullable=True),
    sa.Column('cash_tip', sa.Float(), nullable=True),
    sa.Column('massage_total', sa.Float(), nullable=True),
    sa.Column('facial_total', sa.Float(), nullable=True),
    sa.Column('service_total', sa.Float(), nullable=True),
    sa.Column('total_with_tips', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['work_log_employees.id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['work_log_worksheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_worksheet', 'work_log_entries', ['worksheet_id'], unique=False)
    op.create_table('work_log_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['work_log_employees.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['work_log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_log_entry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('service_code_id', sa.Integer(), nullable=True),
    sa.Column('original_token', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('manually_corrected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['work_log_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_code_id'], ['work_log_codes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_log_ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['work_log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_log_ocr_results')
    op.drop_table('work_log_entry_items')
    op.drop_table('work_log_adjustments')
    op.drop_index('ix_entries_worksheet', table_name='work_log_entries')
    op.drop_table('work_log_entries')
    op.drop_index('ix_worksheets_employee', table_name='work_log_worksheets')
    op.drop_index('ix_worksheets_date', table_name='work_log_worksheets')
    op.drop_index(op.f('ix_work_log_worksheets_date'), table_name='work_log_worksheets')
    op.drop_table('work_log_worksheets')
    op.drop_table('work_log_audit_logs')
    op.drop_table('work_log_employees')
    op.drop_table('work_log_codes')
    # ### end Alembic commands ###
